[project]
name = "deskew"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "driezy", email = "luoyido@outlook.com"},
]
dependencies = [
    "PyMuPDF>=1.24.11",
    "opencv-python>=4.10.0.84",
    "pillow>=10.4.0",
    "deskew>=1.5.1",
    "tqdm>=4.66.5",
]
requires-python = "==3.12.*"
readme = "README.md"
license = {text = "MIT"}


[tool.pdm]
distribution = false
